"Boot with standard options"  "root=UUID=77a8ef2a-4806-4d73-8f71-8fb71eddc19c rw zswap.enabled=0 rootfstype=ext4 loglevel=3 quiet"
"Boot to single-user mode"    "root=UUID=77a8ef2a-4806-4d73-8f71-8fb71eddc19c rw zswap.enabled=0 rootfstype=ext4 loglevel=3 quiet single"
"Boot with minimal options"   "ro root=/dev/nvme0n1p6"
"Boot Arch Linux" "root=/dev/nvme0n1p6 rw quiet splash"
